### PR TITLE
fix: added check to stop creating blank entries

### LINKED ISSUE #8: core: stop creating blank entries
This can happen if a user copies an image. No entry should be made in this case.

### PR DESCRIPTION
**Pull request by morph1nX**
Fixes #8

### CODE REVIEW

**Comment by ayoung19** [comment]
Sorry I pushed up an emergency fix for the tagging feature so there are conflicts now.

Not sure if this was intentional but at first glance I thought the check should go in `offscreen.ts` but it seems like here is better because `updateClipboardSnapshot` will be properly called with the updated blank value.

To make it more obvious that it IS intentional that we call `updateClipboardSnapshot("")` and not `createEntry("")`, can you move this logic to `background/messages/createEntry.ts`? https://github.com/ayoung19/clipboard-history/blob/fe6ad909d4be7998b3d25d5d6b59ad0e87c8fa73/background/messages/createEntry.ts#L25

**Comment by morph1nX** [comment]
Sure, I will do that, makes sense. However, if you can explain something to me:

Why can't we just restrict the `ClipboardSnapshot` and `Entry` types to not take empty content values like this -

```
export const ClipboardSnapshot = z.object({
  content: z.string().min(),
  updatedAt: z.number(),
});
```

In fact, this was my first approach and it did not work

**Comment by ayoung19** [comment]
My apologies for the lack of documentation moving forward I'll do a much better job on that.

Modifying the zod schema doesn't work because validation is only applied during parsing and we only use it to parse when reading from chrome storage.

File: background/messages/createEntry.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ const handler: PlasmoMessaging.MessageHandler<
   CreateEntryRequestBody,
   CreateEntryResponseBody
 > = async (req, res) => {
-  if (req.body && (await getClipboardMonitorIsEnabled())) {
+  if (req.body && req.body.content && (await getClipboardMonitorIsEnabled())) {
```
Comment (ayoung19) [inline background/messages/createEntry.ts:18]: Move the check to line 25. This is because the popup uses `ClipboardSnapshot` to display what's currently copied in the clipboard. We can't just use the most recent entry because copying an item by clicking on it in the popup doesn't update the list.

What can happen now is when a user copies an image `ClipboardSnapshot` won't get updated (line 24). When the user opens up the popup it'll show an item is copied when it actually isn't.

**Comment by ayoung19** [comment]
Oh yeah in the future we'd probably want stricter enforcement on non-blank entries (e.g. a space) so if you have ideas feel free to add on to this! I foresee a setting for the user that's something like "don't copy blank items" and if turned on we can be as aggressive as we'd like with filtering stuff out.
